### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/go-spacemesh#2345]
## Motivation

The API still needs to be documented.

See #1764 

## Changes

- Add a single README file that documents the API implementation (complementary to https://github.com/spacemeshos/SMIPS/issues/21)

## TODO
- [ ] command line flags
- [ ] how to start/stop the grpc services
- [ ] how to start/stop the gateway service
- [ ] how queries work
- [ ] how streams work, the reporter infrastructure (in particular, sending full vs. partial data)
- [ ] error handling: what various endpoints do when given invalid or missing input, or when they find nothing to return, and why these decisions were made, zero max results/huge offsets for queries

## Template

```
# API implementation

This directory contains the go-spacemesh full implementation of the Spacemesh API. This document explains high-level implementation details. It does _not_ discuss API design. For API design, see https://github.com/spacemeshos/api.

## Using the API

Command-line flags

## Architectural overview

## GRPC services

### Queries

### Streams

### Error handling

missing data

## GRPC gateway server

## Reporter
```
