### ISSUE TITLE
save current network state

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2558]
## Description
design and implement a way to save current network state.

## Changes
added a python test to start a network, initiate all nodes (clients, bootstrap and `PoET`) to stop on a certain layer and upload all nodes databases to `Google Cloud Storage` for later use.

## TODO
- [ ] add a `shutdown` endpoint to the `PoET` in order to gracefully shut it down before uploading its data (issued [here](https://github.com/spacemeshos/go-spacemesh/pull/2870))
- [x] add functionality for uploading data from pods to `GCS` (`storage_handler.py`)
- [x] utilize the `shutdown` api endpoint in the miners and bootstrap (`node_api.py`)
- [x] create a test to run a network, stopping all of its components at a certain layer and uploading its data to `GCS` (`test_recorder.py`)
