### ISSUE TITLE
state loading per node in the network

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2559]
## Description
load saved state from `google cloud storage` on each pod in the network - client, bootstrap and poet.
in #2558 a network state was saved to google storage.

this is implemented using the `harness` - a wrapper to the node executable and the `runner` for the PoET.
it gives us the flexibility to download the pods data before running spacemesh.

In order to start each node with different data folder we read all `tar` files under the directory mentioned under `data-dir` config argument and start a node for each file. `list_files_in_path` is the function we use to read all files in the data directory.
The PoET will start with its own `data-path` also being passed using the config arguments list.

## TODO
- [ ] Pass arguments to the PoET, at the moment, for debugging purposes the arguments for the PoET are edited in the PoETs k8s file (e.g., args: [..., '--data-paths', 'DATA_PATH', '--state-bucket', 'BUCKET_NAME']).
- [x] Write mining test that uses the state load functionality (`test_mining_load` -> `test_transactions`)
- [x] Add fixtures to support state loading (`setup_network_with_state`, `setup_clients_with_state`)
- [x] Add functionality for loading clients with preset data dir (`setup_clients_preset_data_dir`)
- [x] Add functionality for loading bootstrap with preset data dir (modified `setup_bootstrap_in_namespace`)
- [x] Add functionality for loading PoET with preset data dir (on the PoET repo added `cmd` -> `runner`)
- [x] Add functionality for downloading files from `GCS` (both in `Spacemesh` and the PoET `common`->`util`->'files'->`Tarxzf`)
