### ISSUE TITLE
Add the poet a new endpoint for shutting down

### ISSUE THREAD

**Issue by AmitShaul** [spacemeshos/go-spacemesh#2619]
## Description
as part of our effort to cut down CI run time - save and load preset PoETs data.
in order to save poets data we first have to stop it at a certain point in time so we can load it later and start from that point exactly.

## TODO
- [x] add a new grpc endpoint for shutting down the poet (`grpc_shutdown`).
- [x] add a wrapping script for the poet so k8s won't restart it once it's down.
- [x] update protobuf on the poet repo
- [ ] add graceful `shutdown` functionality - endpoint functionality sends a panic instead of handling the request gracefully
