### ISSUE TITLE
Move code for generating transactions and addresses in tests into SVM package

### ISSUE THREAD

**Issue by noamnelke** [spacemeshos/go-spacemesh#2829]
Currently, addresses are the the 20-byte suffix of a public key. When we transition to SVM with account abstraction, they will become more complex - a hash of the template address, constructor arguments and some nonce. For the sake of tests at the time we transition to SVM, all accounts will use the same template and nonce, and they'll only differ in their public key (which the only argument to the constructor that changes). Creating an address for tests can be implemented as a function in the SVM package that only receives the public key as an argument.

Since we'll only use a single template for now and we should have a way to predeploy templates - tests will never need to explicitly call `deploy`. However, the first time we use an account, it will have to be spawned.

Create a function for generating a simple spend transaction. Other than the sender's private key, amount and recipient, this function should receive a `bool` called `isFirst` - when true, it returns a "spawn + spend" transaction.

## Tasks
- [ ] `func GenerateAddress(publicKey []byte) Address`
- [ ] `func GenerateSpawnTransaction(signer *signing.EdSigner, target Address) *types.Transaction`
- [ ] `func GenerateCallTransaction(signer *signing.EdSigner, target Address, nonce, amount, gas, fee uint64) *types.Transaction`
- [ ] Use the new functions instead of `types.NewSignedTx()` and similar functions (e.g. the 7 implementations of `NewTx()` that we have in different tests).

**Comment by neysofu** [comment]
@nkryuchkov as I'm busy on the Rust side of SVM, it would be great if you could work on this. Ping me if you have any questions, tomorrow/following days I can walk you through the context that you need to implement this issue if you want. Let me know what day works best for you.

Once this task is complete, we most likely want to start pulling in `go-svm` as a `go-spacemesh` depedency and phase out the `svm/state` package in favor of `go-svm` itself. This is documented under the "Phase 3" of https://github.com/spacemeshos/pm/issues/89 and, depending on our availability, we might share the workload or you might do most of it yourself. Pulling in `go-svm` requires changes to the Makefile and fiddling with CGo; I'm not sure how familiar you are with it but I guess it makes more sense for me to handle that since I did the original CGo-related work on `go-svm`.

**Comment by nkryuchkov** [comment]
@neysofu Thanks for the details. I'll work on this. Let's discuss that tomorrow. I'm familiar with the Cgo, but will ask you if any questions appear
