### ISSUE TITLE
node: continue to advance despite poet server failures

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3381]
### background
while doing longevity testing, the following scenario happened and the network simply halted.
the one PoET server became unstable in epoch 22 and requests to build NIPost all failed. 
this means miners cannot build ATXs to target epoch 23,

when epoch 24 starts, several components starts to fail due to cascade of multiple events
- miners cannot participate in beacon protocol (no ATX in epoch 23)
- miners cannot build proposals as it cannot calculate its own eligibility (no ATX in epoch 23)
- nodes fell out of sync when the latest known layer is too far behind current layer
- hare cannot run consensus protocol (nodes go out of sync, no ATX in epoch 23)
- tortoise cannot verify layers as no proposal/ballots are produced

basically the network halted.

and even if PoET servers recover, and ATXs building resumes, the code as is, cannot recover because syncer 
doesn't detect layers with absolutely zero content (no ballot and blocks).

this means that
- we need to have HighAvailability for PoET servers
- syncer needs to be able to make progress when hare doesn't (currently syncing data from peers is gated at processed layer) and when the network stopped producing ballots/blocks for many many layers
- tortoise needs to be able to produce votes when ballots are unavailable for many many layers

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3440 syncer: move the network forward despite layers of empty content
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3388 tortoise: continue to verify layers despite long period of emptiness
- [ ] https://github.com/spacemeshos/go-spacemesh/issues/3441 activation: resumes building atxs after poet servers recover
