### ISSUE TITLE
hare: equivocation mitigation for genesis

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#3915]
# description

research discussion: https://community.spacemesh.io/t/hare-equivocations-defense/329
the goal of this implementation is to mitigate hare equivocations for genesis. 

# implementation Plan
we will
- detect malfeasance behavior below and generate a `MalfeasanceProof` for an identity
  - miners that publish multiple ATXs targeting the same epoch
  - miners that publish multiple ballots for the same layer
  - miners that equivocates in the hare protocol
- gossip `MalfeasanceProof` and optionally the hare eligibility proof for the malicious identity
  (see `MalfeasanceGossip` below)
- save `MalfeasanceProof` in the mesh
- add `EligibilityType` to the input message for VRF to differentiate different types of eligibility
- allow a malicious identity to participate in the hare protocol, but wherever `f+1` is applied for a
  given layer/round, replace with `f+1-k` where `k` is the number of eligible identity in the layer/round
  with a `MalfeasanceProof`
- process gossiped `MalfeasanceProof` and save one per identity
- new node: sync `MalfeasanceProof` as part of the sync flows

we will not
- retroactively invalidate data published by a malicious identity
- ban a malicious identity from participating the hare protocol

## malfeasance behavior
- miners that publish multiple ATXs targeting the same epoch
- miners that publish multiple ballots for the same layer
- miners that equivocates in the hare protocol

## malfeasance proof
```go
type MalfeasanceType uint16

const (
	MultipleATXs MalfeasanceType = iota + 1
	MultipleBlockProposals
	HareEquivocation
)

type MalfeasanceProof struct {  // persisted
        // for network upgrade
       Layer LayerID
       Type MalfeasanceType
        // conflicting messages signed by the same NodeID
       Messages []Object
}

type MalfeasanceGossip struct {
	Proof MalfeasanceProof
        // optional, only useful in live hare rounds
	Eligibility *Eligibility
}

type Eligibility struct {
        // for hare rounds or ballot votes
	Type EligibilityType
	PubKey []byte
        // list of proofs.
        // M proofs of HareEligibility where the identity is eligible in M layer/rounds 
        // N proofs of VotingEligibilityProof where the identity has N slots in an epoch
	Proofs [][]byte
}

type HareEligibility struct {
        // VRF signature of EligibilityType, beacon, layer, round
	Proof []byte
	// the eligibility count for this layer, round
	Count uint16
}

type VotingEligibility struct {  // persisted
	// if the value of J is 3, this is the smesher's eligibility proof of the 3rd ballot in the epoch.
	J uint32
	// the VRF signature of EligibilityType, beacon, epoch and J.
	Sig []byte
}
```

## existing data structures

changes to data structures are based on the following considerations:
- done to all data types that could be included in a `MalfeasanceProof` to avoid post-genesis data structure change
- easy verification of `MalfeasanceProof` without extra data 
- minimize size of `MalfeasanceProof` data as the proof are stored in the mesh forever 
  (signature over hash of message instead of message itself)
- adhere to rules for network upgrade per https://github.com/spacemeshos/go-spacemesh/issues/3211
- (non-goal) separate data that can be independently verified
  (vrfKey signed (eligibility) versus edKey signed (gossip messages))

below are the data types that will be modified and their corresponding conflicting messages in the `MalfeasanceProof`.
### ActivationTx
before:
```go
type ActivationTx struct {
	InnerActivationTx
	// signature over InnerActivationTx
	Signature []byte
}
```
after:
```go
type ATXMetadata struct {
	TargetEpoch EpochID
        // hash of InnerActivationTx
	MsgHash Hash32 
}

type ActivationTx struct {
	InnerActivationTx
	Metadata ATXMetadata
	// signature over Metadata
	Signature []byte 
}
```
malfeasance message
```go
type InnerMultiATXsMsg struct {
	TargetEpoch EpochID
	MsgHash Hash32
}

type MultiATXsMsg struct {
	InnerMsg  InnerMultiATXsMsg
	Signature []byte
}
```

### Ballot
before:
```go
type Ballot struct {
	InnerBallot 
	// signature on InnertBallot
	Signature []byte
	Votes Votes
}
```
after:
```go
type BallotMetadata struct {
        // moved from InnerBallot, for network upgrade
	Layer LayerID
	// hash of InnerBallot
	MsgHash Hash32
}

type Ballot struct {
	BallotMetadata
	// signature over BallotMetadata
	Signature []byte
	InnerBallot
	Votes Votes
	// moved from InnerBallot
        EligibilityProofs []VotingEligibility
}
```
malfeasance message:
```go
type InnerMultiBlockProposalsMsg struct {
	Layer LayerID
	MsgHash Hash32
}

type MultiBlockProposalsMsg struct {
	InnerMsg InnerMultiBlockProposalsMsg
	Signature []byte
}
```

### hare.Message

before:
```go
type Message struct {
	InnerMsg *InnerMessage
        // signature over InnerMsg
	Signature []byte
}
```
after:
```go
type Metadata struct {
        // layer
	InstanceID types.LayerID
        // round
	K uint32
	// hash of InnerMsg
	MsgHash types.Hash32 
}

type Message struct {
	Metadata
	// signature over Metadata
	Signature []byte
	InnerMsg *InnerMessage
	// moved from InnerMsg
	Eligibility types.HareEligibility
}
```
malfeasance message:
```go
type InnerHareEquivocationMsg struct {
	Layer LayerID
	Round RoundID
	MsgHash Hash32
}

type HareEquivocationMsg struct {
	InnerMsg InnerHareEquivocationMsg
	Signature []byte
}
```

## hare
below are the places in hare where `f+1` rule is applied
- preround: determine whether each value has at least `f+1` support.
- status round: determine whether there are at least `f+1` status messages to build a safe value proof (SVP)
- commit round: determine whether there are at least `f+1` commit messages to to build a commit certificate
- notify round: validate the commit messages in the received commit certificate
- notify round: determine whether there are at least `f+1` notify messages to terminate the hare instance

the new `f+1-k` rule will be used wherever `f+1` rule is applied currently.

note: the `k` malicious identity must also be eligible for the given layer and round. this is why the `HareEligibility` needs to be gossiped along with the `MalfeasanceProof` in live hare rounds, hence `MalfeasanceGossip`. the `HareEligibility` messages also need to be kept for the duration of a hare instance, as the node will need to verify earlier round messages when validating the commit messages in the commit certificate.

## block certificate
- generating: `f+1` valid `CertifyMessage`
  wait for `f+1` valid `CertifyMessage` before generating a block certificate. all `CeritfyMessage` need to be 
  from eligible and non-malicious identity.
- validating a synced certificate: `f+1-k` valid `CertifyMessage`
  accept a certificate if there are `f+1` valid `CeritfyMessage` from eligible identities, of which the maximum 
  number of malicious identities is `k`.

## sync
`MalfeasanceProof` will be treated like ATXs during sync flow. once the node is atxSynced, it will start listening to `MalfeasanceGossip` and save network's `MalfeasanceProof` locally.

note: a not-synced node is capable of validating `MalfeasanceProof` without the actual conflicting atxs/ballots/hare messages.

## work planning

- [x] https://github.com/spacemeshos/go-spacemesh/issues/3918 => NOOP
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3919 => NOOP
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3920 => NOOP
- [x] https://github.com/spacemeshos/go-spacemesh/issues/3921

#### Q1: should a malicious identity proven through multiple ATXs in the same epoch be treated the same way as a malicious identity proven through hare equivocation?
i.e. hare accepts all types of MalfeasanceProof as long as the identity is eligible in the given layer/round?

#### Q2: how should we treat ATXs from a malicious identity? 
- are they eligible for beacon protocol also?
- does it count towards the total epoch weight? (tortoise active set) it should as we are accepting malicious ballots at zero weight.
- should the node save the subsequent ATXs from the malicious identity?
  - if not, presumably different nodes will have different 1st ATX from the malicious identity, causing different views of active set in the network
  - if yes, do all of them count towards the epoch weight? participate in beacon/hare protocols?

**Comment by dshulyak** [comment]
Signature in the proofs is unnecessary. It doesn't change anything in the validation of the proof. It will become super obvious during implementation

```go
type InnerMalfeasanceProof struct {
        // for network upgrade
	Layer LayerID
	Type MalfeasanceType
        // conflicting messages signed by the same NodeID
        // one of MultiATXsMsg, MultiBlockProposalsMsg and HareEquivocationMsg
	Messages [][]byte
}
```

This can be improved to 

```go
type Proof struct {
     Layer
     Type Type
     Message []Object
}
```

Where Object is an interface, created based on the Type value. There is even a special type for that in scale, you will avoid multiple unnecessary allocation for encoding/decoding in the code path. and generally it is much cleaner and somewhat shorter

**Comment by countvonzero** [comment]
> Signature in the proofs is unnecessary. It doesn't change anything in the validation of the proof. It will become super obvious during implementation

yes it's already obvious to me now. i'm inclined to do without the signature in the first place. tho i am not sure whether we will end up punishing miners that publish invalid `MalfeasanceProof`. it's that's part of the plan, then i'd rather change the data now and minimize change post-genesis. i'll confirm this with research in the next call.
 
> Where Object is an interface, created based on the Type value. There is even a special type for that in scale, you will avoid multiple unnecessary allocation for encoding/decoding in the code path. and generally it is much cleaner and somewhat shorter

thanks for the tip. curious what the special type in scale that is. can you share @dshulyak ?
i assume you meant replacing the `Type` with a scale built-in type. if so, we may require a network upgrade if we replace scale with some other encoding scheme?

**Comment by dshulyak** [comment]
> i assume you meant replacing the Type with a scale built-in type

scale type is Enumeration, there is no out of the box support for it in spacemeshos/go-scale
it is just a uint8 followed by an actual type, though that lib always encodes integers in compact form
i would probably just do an incremental decoding, if you don't want to change go-scale

> if so, we may require a network upgrade if we replace scale with some other encoding scheme?

every type is encoded with scale, switching it to anything will require upgrade, this particular case is not special

**Comment by selfdual-brain** [comment]
Publishing invalid `MalfeasanceProofs` is an attack angle we already discussed in Lisbon. Another such attack - somewhat funny - is to equivocate with malfeasance proofs. Publishing more than one proof of malfeasance for the same subject is considered an equivocation.

Although we are already prepared to mitigate the second type of attacks by smart gossip, I assume that a malfeasance proof should be signed and that we will validate this signature because we have good reasons to do so (I am not sure though if I am getting right the discussion above about removing a signature - ?).

**Comment by countvonzero** [comment]
@dshulyak per research meeting on Jan 2nd 2022, we don't need signature for `MalfeasanceProof`.
for nodes that gossip about an invalid `MalfeasanceProof`, we simply drop the node as direct peer, and/or lower the gossip score for this peer.
