### ISSUE TITLE
implement hare active set

### ISSUE THREAD

**Issue by countvonzero** [spacemeshos/go-spacemesh#4089]
## background

prior to unified content block, the hare active set was derived from contextually valid blocks verified by tortoise, hence are in consensus.
after unified content block, the hare active set was derived from first ballot of epoch from smeshers. since nodes do not have consensus on ballots, this active set is not in consensus

## proposal

- implement https://community.spacemesh.io/t/grading-atxs-for-the-active-set/335
- hare active set for epoch E will be derived from the first block in epoch E in the following way:
  - take the proposals produced by the ATXIDs recorded in the block
  - the union of the active set referenced by said proposals is used as the hare active set for epoch E (plus safe layer range)
- newly synced node (not online last epoch to receive ATXs real time) will use the first block of current epoch and for the active set in its ballot

## bootstrapping and recovery
a spacemesh signed active set (a list of ATX IDs) will b used for
- the first safe layer range in epoch 2.
- when hare fails to reach consensus after N layers for any given epoch

## implementation plan
- [ ] https://github.com/spacemeshos/go-spacemesh/pull/4148 use atx grading scheme in reference ballot and hare
- [x] https://github.com/spacemeshos/go-spacemesh/pull/4231 binary that publishes bootstrap and fallback values for beacon and active set
- [x] https://github.com/spacemeshos/go-spacemesh/pull/4241 bootstrap and use first consensus block for hare active set
